version: "3.9"

services:
  sessions:
    image: redis:alpine
    container_name: sessions_redis
    restart: unless-stopped
    ports:
      - 3030:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - ./redis/data/:/data/
    networks:
      - ms-poc
  
  users_db:
    image: postgres:alpine
    container_name: users_db_postgresql
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 4040:5432
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    networks:
      - ms-poc
  
  users:
    build: 
      context: ./users/
      dockerfile: Dockerfile
    container_name: users_node
    restart: always
    ports: 
      - 5050:5055
    volumes:
      - ./users/:/app/
    networks:
      - ms-poc
    depends_on:
      - users_db
    links:
      - users_db

networks:
  ms-poc:
    driver: bridge

